import './globals.css'
import Header from './Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head/>

      <body className='bg-[#EAEBE4] dark:bg-zinc-700 transition-all duration-700'>
        <Header />
        <div className='max-w-6xl mx-auto'>{children}</div>
        </body>
    </html>
  )
}
